apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-client
  namespace: default
  labels:
    app: cilium-client
    environment: toolkit
    app_name: cilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilium-client
  template:
    metadata:
      labels:
        app: cilium-client
        environment: toolkit
        app_name: cilium
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
---

apiVersion: v1
kind: Service
metadata:
  name: cilium-client-svc
  namespace: default
  labels:
    app: cilium-client
spec:
  selector:
    app: cilium-client
  type: ClusterIP
  ports:
  - name: cilium-client
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cilium-client
  namespace: default
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cilium-client-svc
            port:
              number: 80
