global:
   enabled: true
   tlsDisable: true
injector:
   enabled: true
ui:
   enabled: true
   serviceType: "LoadBalancer"
server:
   dataStorage:
      storageClass: standard
   ha:
      enabled: true
      replicas: 3
      raft:
         enabled: true
         setNodeId: true
         config: |
            ui = true
            cluster_name = "vault-integrated-storage"
            storage "raft" {
               path  = "/vault/data/"
            }

            listener "tcp" {
               address = "0.0.0.0:8200"
               cluster_address = "0.0.0.0:8201"
               tls_disable = "true"
            }
            service_registration "kubernetes" {}
