apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-client
  namespace: operations
  labels:
    app: vault-client-app
spec:
  selector:
    matchLabels:
      app: vault-client-app
  template:
    metadata:
      labels:
        app: vault-client-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "operation-role"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "operations/webapp" -}}
          export USERNAME="{{ .Data.data.username_psql }}"
          export PASSWORD="{{ .Data.data.password_psql }}"
          {{- end }}
    spec:
      serviceAccountName: operation-sa
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault:8200"
        - name: JWT_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: SERVICE_PORT
          value: "80"
