# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
resource "random_password" "generated" {
  count   = var.count_replaced_on_create
  length           = var.length
  special          = var.special
  override_special = var.override_special
  upper            = var.upper
  numeric          = var.numeric
}

variable "count_replaced_on_create" {
  description = "Number of passwords to generate"
  type        = number
  default     = 1
  
}

variable "length" {
  description = "Length of the generated password"
  type        = number
  default     = 16
}

variable "special" {
  description = "Include special characters in the password"
  type        = bool
  default     = true
}

variable "override_special" {
  description = "Override the special characters used in the password"
  type        = string
  default     = "!#$%&*()-_=+[]{}<>:?"
}

variable "upper" {
  description = "Include uppercase letters in the password"
  type        = bool
  default     = true
}

variable "numeric" {
  description = "Include numeric characters in the password"
  type        = bool
  default     = true
}


output "generated_password" {
  value     = random_password.generated[*].result
  sensitive = true
}
