server:
  dev:
    enabled: true
ui:
  enabled: true
  activeVaultPodOnly: false
  serviceType: "LoadBalancer"
ingress:
  enabled: true
  hosts:
  - host: vault.kind.internal
    paths:
    - path: /
      pathType: Prefix
