---
- hosts: localhost
  become: true
  vars:
    dns_ip: "{{ dns_ip }}"
    dns_host: "{{ dns_host }}"
  roles:
    - role: 'resolv'
      become: true
      resolv_nameservers:
        - 127.0.0.1
        - 8.8.8.8
        - 1.1.1.1
    - role: 'dnsmaq'
      become: true
