apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-lb-all-services
spec:
  nodeSelector:
    matchLabels:
      homelab/role: worker
  serviceSelector:
    matchLabels:
      homelab/public-service: "true"
  loadBalancerIPs: true
---

apiVersion: v1
kind: Service
metadata:
  name: cilium-test-lb-svc
  labels:
    app: cilium-test-lb
spec:
  selector:
    app: cilium-test-lb
  type: LoadBalancer
  ports:
  - name: cilium-test-lb
    protocol: TCP
    port: 80
    targetPort: 80
